### ISSUE TITLE
Which different point compared with Unit Test. 

### ISSUE THREAD

**Issue by Accagain2014** [ShallYan/AutoTest#1]
Ha ha ha ...

**Comment by shallyan** [comment]
You don't need to wirte "main" and test code like following lines:
if (func(xx,yy) != zz) 
     then... 
else if (func(xx2,yy2) != zz2)
     then... 
And you don't need to compile the code, run the code and check the results manually.
What you have to do is to write your function and the test cases, then run the tool.
